name: EusMapDisplay
version: 1.0
main: cc.eumc.eusmapdisplay.EusMapDisplay
api-version: 1.17
authors: [ EucalyptusLeaves ]
website: www.eumc.cc
commands:
  mapdisplay:
permissions:
  mapdisplay.admin:
    default: op
    description: Permission for EusMapDisplay administorators' commands